export interface KnowledgeChunk {
  id: string;
  source: string;
  section: string;
  entity: string;
  category: 'identity' | 'education' | 'skills' | 'project' | 'experience' | 'leadership';
  title: string;
  content: string;
  technologies?: string[];
  keywords: string[];
  page: number;
  source_type: 'resume';
}

export const KNOWLEDGE_BASE: KnowledgeChunk[] = [
  {
    id: 'resume-identity',
    source: 'Suyash Singh Resume',
    section: 'Header / Identity',
    entity: 'Suyash Singh',
    category: 'identity',
    title: 'Suyash Singh — Identity & Verified Links',
    content:
      'Suyash Singh is a Computer Science Engineering (Data Science) undergraduate at Manipal Institute of Technology (graduating 2027) with a strong foundation in full-stack engineering, distributed systems, AI agent observability, and machine learning pipelines. Public profile links: Portfolio Website (https://suyash.website), LinkedIn (linkedin.com/in/suyashin), GitHub (github.com/anothercodingguy), Email (suyashs787@gmail.com), Phone (+91 8604960115).',
    keywords: [
      'who is suyash',
      'about suyash',
      'suyash bio',
      'profile',
      'bio',
      'portfolio',
      'website',
      'site',
      'github',
      'linkedin',
      'contact',
      'email',
      'phone',
      'identity',
      'about',
    ],
    page: 1,
    source_type: 'resume',
  },
  {
    id: 'resume-education',
    source: 'Suyash Singh Resume',
    section: 'Education',
    entity: 'Manipal Institute of Technology',
    category: 'education',
    title: 'Education — Manipal Institute of Technology',
    content:
      'Manipal Institute of Technology, Bengaluru, India. B.Tech in Computer Science Engineering (Data Science). Expected Graduation: 2027. CGPA: 8.51/10. Strong foundation in Computer Science fundamentals, Data Structures & Algorithms, and full-stack development.',
    keywords: [
      'education',
      'college',
      'university',
      'degree',
      'study',
      'studies',
      'btech',
      'b.tech',
      'data science',
      'manipal',
      'manipal institute of technology',
      'mit',
      'cgpa',
      'gpa',
      'marks',
      'graduation',
      '2027',
      'bengaluru',
      'cs fundamentals',
    ],
    page: 1,
    source_type: 'resume',
  },
  {
    id: 'resume-skills-fundamentals',
    source: 'Suyash Singh Resume',
    section: 'Technical Skills',
    entity: 'Core Fundamentals & Languages',
    category: 'skills',
    title: 'Technical Skills — Core Fundamentals & Languages',
    content:
      'Core Fundamentals: Data Structures & Algorithms (DSA), Object-Oriented Design (OOD), System Design, Operating Systems. Languages: Java, C++, Python, TypeScript, JavaScript (ES6+), SQL.',
    technologies: ['Java', 'C++', 'Python', 'TypeScript', 'JavaScript', 'SQL', 'DSA', 'System Design', 'OOD', 'OS'],
    keywords: [
      'skills',
      'languages',
      'programming languages',
      'java',
      'c++',
      'python',
      'typescript',
      'javascript',
      'sql',
      'system design',
      'data structures',
      'algorithms',
      'dsa',
      'ood',
      'operating systems',
    ],
    page: 1,
    source_type: 'resume',
  },
  {
    id: 'resume-skills-backend-cloud',
    source: 'Suyash Singh Resume',
    section: 'Technical Skills',
    entity: 'Backend & Cloud Infrastructure',
    category: 'skills',
    title: 'Technical Skills — Backend, Cloud & Observability',
    content:
      'Backend & Cloud: Node.js, Express.js, FastAPI, REST APIs, Microservices, Docker, Kubernetes, NATS, KEDA, AWS, GCP. Observability & Data: Prometheus, Grafana, Redis, PostgreSQL, MongoDB, Qdrant Vector DB, Upstash.',
    technologies: [
      'Node.js',
      'Express.js',
      'FastAPI',
      'REST APIs',
      'Microservices',
      'Docker',
      'Kubernetes',
      'NATS',
      'KEDA',
      'AWS',
      'GCP',
      'Prometheus',
      'Grafana',
      'Redis',
      'PostgreSQL',
      'MongoDB',
      'Qdrant',
      'Upstash',
    ],
    keywords: [
      'backend',
      'cloud',
      'infrastructure',
      'fastapi',
      'node',
      'nodejs',
      'express',
      'docker',
      'kubernetes',
      'k8s',
      'nats',
      'keda',
      'aws',
      'gcp',
      'redis',
      'postgres',
      'postgresql',
      'mongodb',
      'qdrant',
      'prometheus',
      'grafana',
      'upstash',
      'database',
    ],
    page: 1,
    source_type: 'resume',
  },
  {
    id: 'resume-skills-ml-cp',
    source: 'Suyash Singh Resume',
    section: 'Technical Skills',
    entity: 'Machine Learning & Competitive Programming',
    category: 'skills',
    title: 'Technical Skills — ML/AI & Competitive Programming',
    content:
      'ML / AI: PyTorch, LLM Pipelines, RAG Frameworks, Machine Unlearning Pipelines. Competitive Programming: LeetCode (200+ Problems Solved) | Codeforces Pupil (1224 Max Rating) | CodeChef 3★ (Problem Solving & Python).',
    technologies: ['PyTorch', 'LLM Pipelines', 'RAG Frameworks', 'Machine Unlearning'],
    keywords: [
      'ml',
      'ai',
      'machine learning',
      'pytorch',
      'llm',
      'rag',
      'machine unlearning',
      'competitive programming',
      'leetcode',
      'codeforces',
      'codechef',
      'rating',
      'pupil',
      '3 star',
      'problem solving',
    ],
    page: 1,
    source_type: 'resume',
  },
  {
    id: 'resume-project-pathflow',
    source: 'Suyash Singh Resume',
    section: 'Technical Projects',
    entity: 'PathFlow',
    category: 'project',
    title: 'Project — PathFlow ("Strava for AI Agents")',
    content:
      'PathFlow — "Strava for AI Agents". Technologies: Next.js 15, TypeScript, Tailwind CSS, React Flow, Prisma, OpenTelemetry, Python. System Architecture: Architected an OpenTelemetry-compatible observability platform to track execution paths, token velocity (t/s), context volume, and API compute costs across autonomous agent fleets. Interactive Visualization: Built an interactive DAG visualizer with React Flow to inspect multi-step agent execution trees, sub-span latencies, and tool-routing decisions in real-time. Benchmarking & Telemetry: Engineered a multi-factor skill benchmarking engine ranking agents by micro-segment (Score = Success Rate × Efficiency × Novelty × Difficulty) and a lightweight Python SDK (@pf.trace) streaming spans to the ingestion API.',
    technologies: ['Next.js 15', 'TypeScript', 'Tailwind CSS', 'React Flow', 'Prisma', 'OpenTelemetry', 'Python'],
    keywords: [
      'pathflow',
      'strava for ai agents',
      'agent observability',
      'dag',
      'dag visualizer',
      'react flow',
      'execution tree',
      'execution paths',
      'token velocity',
      'context volume',
      'compute costs',
      'benchmarking',
      'ranking formula',
      '@pf.trace',
      'opentelemetry',
      'prisma',
      'visualization',
      'agent fleet',
      'tool-routing',
    ],
    page: 1,
    source_type: 'resume',
  },
  {
    id: 'resume-project-semantic-llm',
    source: 'Suyash Singh Resume',
    section: 'Technical Projects',
    entity: 'Semantic LLM Gateway & Routing Proxy',
    category: 'project',
    title: 'Project — Semantic LLM Gateway & Routing Proxy',
    content:
      'Semantic LLM Gateway & Routing Proxy. Technologies: FastAPI, Qdrant, Redis, Hugging Face, Groq, Ollama. System Design: Built a production-grade, AI-integrated proxy with Qdrant-backed semantic caching, drastically reducing redundant LLM API calls and achieving cache-hit latencies under 50ms. Complex Routing: Implemented dynamic intent routing to classify prompt complexity, intelligently distributing concurrent loads across high-performance and lightweight models to optimize resource utilization. Fault Tolerance: Engineered a robust circuit-breaker fallback mechanism, maintaining zero-downtime reliability and high availability during upstream rate limits or network outages.',
    technologies: ['FastAPI', 'Qdrant', 'Redis', 'Hugging Face', 'Groq', 'Ollama'],
    keywords: [
      'semantic llm gateway',
      'routing proxy',
      'gateway',
      'proxy',
      'semantic caching',
      'qdrant',
      'under 50ms',
      'cache-hit',
      '50ms',
      'dynamic intent routing',
      'prompt complexity',
      'circuit-breaker',
      'circuit breaker',
      'fault tolerance',
      'groq',
      'ollama',
      'hugging face',
      'fastapi',
    ],
    page: 1,
    source_type: 'resume',
  },
  {
    id: 'resume-project-reachinbox',
    source: 'Suyash Singh Resume',
    section: 'Technical Projects',
    entity: 'ReachInbox Full-Stack Email Scheduler',
    category: 'project',
    title: 'Project — ReachInbox Full-Stack Email Scheduler',
    content:
      'ReachInbox Full-Stack Email Scheduler. Technologies: TypeScript, Next.js, Node.js, Redis. Scalable Architecture: Architected and deployed a highly concurrent email scheduling system using Next.js and Redis, ensuring reliable asynchronous task execution across distributed queues. Full-Stack Engineering: Designed responsive interfaces and optimized backend data pipelines, successfully demonstrating the versatility required to solve problems across the entire software stack.',
    technologies: ['TypeScript', 'Next.js', 'Node.js', 'Redis'],
    keywords: [
      'reachinbox',
      'email scheduler',
      'email',
      'scheduler',
      'distributed queues',
      'asynchronous task execution',
      'redis queue',
      'full stack',
    ],
    page: 1,
    source_type: 'resume',
  },
  {
    id: 'resume-project-senns',
    source: 'Suyash Singh Resume',
    section: 'Technical Projects',
    entity: 'Self-Erasing Neural Networks (SENNs)',
    category: 'project',
    title: 'Research — Self-Erasing Neural Networks (SENNs), ICDDS 2025',
    content:
      'Self-Erasing Neural Networks (SENNs) Research Publication, ICDDS 2025. Technologies: Python, PyTorch, Data Structures & Algorithms. Experimental Systems: Co-authored a peer-reviewed paper designing a complex algorithmic framework for GDPR-compliant machine unlearning, accepted at the ICDDS 2025 international conference. Data Analysis & Visualization: Developed rigorous diagnostic pipelines to evaluate weight shifts and per-class accuracy trade-offs, visualizing performance metrics across gradient-based data erasure models.',
    technologies: ['Python', 'PyTorch', 'Data Structures & Algorithms'],
    keywords: [
      'senns',
      'senn',
      'self-erasing neural networks',
      'research',
      'paper',
      'publication',
      'icdds',
      'icdds 2025',
      'gdpr',
      'machine unlearning',
      'unlearning',
      'gradient-based data erasure',
      'weight shifts',
      'accuracy trade-offs',
      'pytorch',
    ],
    page: 1,
    source_type: 'resume',
  },
  {
    id: 'resume-experience-stealth',
    source: 'Suyash Singh Resume',
    section: 'Work Experience',
    entity: 'Stealth Startup',
    category: 'experience',
    title: 'Work Experience — AI Intern at Stealth Startup',
    content:
      'Stealth Startup (Dec. 2025 – May 2026), AI Intern, Bengaluru, India. Architected and deployed scalable REST APIs and distributed inference pipelines on AWS, engineering highly concurrent state machine logic and multi-turn session management. Engineered intelligent routing logic and resilient backend services, optimizing concurrent request handling and backend fault tolerance.',
    technologies: ['AWS', 'REST APIs', 'Distributed Inference', 'State Machines'],
    keywords: [
      'stealth startup',
      'stealth',
      'ai intern',
      'internship',
      'work experience',
      'experience',
      'aws',
      'inference pipelines',
      'state machine',
      'multi-turn session',
      'session management',
      'dec 2025',
      'may 2026',
    ],
    page: 1,
    source_type: 'resume',
  },
  {
    id: 'resume-experience-ieee',
    source: 'Suyash Singh Resume',
    section: 'Work Experience',
    entity: 'IEEE Computer Society Bangalore Chapter',
    category: 'experience',
    title: 'Work Experience — R&D Intern at IEEE Computer Society',
    content:
      'IEEE Computer Society Bangalore Chapter (Apr. 2025 – Sept. 2025), R&D Intern, Bengaluru, India. Evaluated complex distributed architectures and AI research to build production-ready reference implementations. Analyzed system performance metrics and log data to validate architectural reliability across distributed nodes.',
    technologies: ['Distributed Architectures', 'AI Research', 'Performance Metrics', 'Log Analysis'],
    keywords: [
      'ieee',
      'ieee computer society',
      'bangalore chapter',
      'r&d intern',
      'research and development',
      'internship',
      'distributed architectures',
      'distributed nodes',
      'apr 2025',
      'sept 2025',
    ],
    page: 1,
    source_type: 'resume',
  },
  {
    id: 'resume-leadership-mbosc',
    source: 'Suyash Singh Resume',
    section: 'Positions of Responsibility',
    entity: 'Manipal Bengaluru Open-Source Community (MBOSC)',
    category: 'leadership',
    title: 'Leadership — Project Head at MBOSC',
    content:
      'Manipal Bengaluru Open-Source Community (MBOSC) (2024 – 2025), Project Head. Mentored 200+ student developers on system architecture, Git workflows, and open-source contributions, leading code reviews and encouraging software design best practices.',
    keywords: [
      'leadership',
      'mbosc',
      'manipal bengaluru open-source community',
      'open source',
      'project head',
      'mentored 200+',
      'mentorship',
      'git workflows',
      'code reviews',
      '2024',
      '2025',
    ],
    page: 1,
    source_type: 'resume',
  },
  {
    id: 'resume-leadership-codex',
    source: 'Suyash Singh Resume',
    section: 'Positions of Responsibility',
    entity: 'Codex (Competitive Programming Club)',
    category: 'leadership',
    title: 'Leadership — Project Head at Codex',
    content:
      'Codex (Competitive programming club) (2025), Project Head. Led competitive programming initiatives and mentorship at Manipal Institute of Technology.',
    keywords: ['codex', 'competitive programming club', 'project head', '2025', 'leadership'],
    page: 1,
    source_type: 'resume',
  },
];
